# Site settings
title: Board Gamers of Hyderabad
email: boardgamersofhyderabad@gmail.com
description: Official Website for the Board Gamers of Hyderabad
author: Himanshu
version: v1
header_title: BGH
url: https://boardgamersofhyderabad.github.io

webmaster_verifications:
  google: g8exolt2RkC5fxYlQ5nWatqvnFhHE0x_lYIa-W5ya8Q

fonts:
  heading: Oswald
  content: Roboto

#Event images
defaults:
  - scope:
      path: "eventImages"
    values:
      image: true

#Social Media Profile
sociallinks:
  Facebook: https://www.facebook.com/
  Instagram: https://www.instagram.com/
  WhatsApp: https://www.whatsapp.com/
  Meetup: https://www.meetup.com/
  BGG: https://boardgamegeek.com/guild/3493

# Build settings
markdown: kramdown

plugins:
  - jekyll-seo-tag