# Site settings
title: Board Gamers of Hyderabad
email: boardgamersofhyderabad@gmail.com
<<<<<<< HEAD
description: Official Website for the Board Gamers of Hyderabad
=======
description: Official Website for Board Gamers of Hyderabad
>>>>>>> 8961445b561869f6b8364e4acbfd09a97e7c78cd
author: Himanshu
version: v1
header_title: BGH
url: https://boardgamersofhyderabad.github.io/


fonts:
  heading: Oswald
  content: Roboto

#Event images
defaults:
  - scope:
      path: "eventImages"
    values:
      image: true

#Social Media Profile
sociallinks:
  Facebook: https://www.facebook.com/
  Instagram: https://www.instagram.com/
  WhatsApp: https://www.whatsapp.com/
  Meetup: https://www.meetup.com/

# Build settings
markdown: kramdown